trigger:
- main

pool:
  name: Default   # your agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

# 🔥 DEPLOYMENT
- script: |
    echo "Simulating deployment..."
    mkdir deployed
    copy target\*.jar deployed
    echo "Deployment successful!"
  displayName: 'Simulate Deployment'

# 🔥 RUN APPLICATION
- script: |
    echo "Running the JAR file..."
    java -jar deployed\maven-proj-1.0-SNAPSHOT.jar
  displayName: 'Run Application'